SELECT *
FROM EXOPLANETS;


--2nd query checking for null values


SELECT
COUNT(*) FILTER (WHERE distance IS NULL) AS distance_nulls,
COUNT(*) FILTER (WHERE mass_multiplier IS NULL) AS mass_nulls,
COUNT(*) FILTER (WHERE radius_multiplier IS NULL) AS radius_nulls,
COUNT(*) FILTER (WHERE orbital_period IS NULL) AS orbital_nulls
FROM exoplanets;  


-- Remove completely useless rows


DELETE FROM exoplanets
WHERE mass_multiplier IS NULL
  AND radius_multiplier IS NULL;



-- Handle missing values

CREATE VIEW CLEAN_EXOPLANETS AS
SELECT *
FROM exoplanets
WHERE distance IS NOT NULL
  AND orbital_period IS NOT NULL;


-- REMOVING DUPLICATES 

SELECT NAME,COUNT(*)
FROM EXOPLANETS 
GROUP BY 1
HAVING COUNT(*)>1;


--DELETING DUPLICATES

DELETE FROM EXOPLANETS E1
USING EXOPLANETS E2
WHERE E1.CTID<E2.CTID AND E1.NAME = E2.NAME


--STANDARDIZING TEXT 


UPDATE EXOPLANETS
SET PLANET_TYPE = TRIM(LOWER(PLANET_TYPE))


UPDATE EXOPLANETS
SET DETECTION_METHOD = TRIM(LOWER(DETECTION_METHOD))



--CREATING DERIVED COLUMN 

ALTER TABLE EXOPLANETS 
ADD COLUMN MASS_JUPITER DOUBLE PRECISION;

UPDATE EXOPLANETS
SET MASS_JUPITER = MASS_MULTIPLIER
WHERE MASS_WRT = 'JUPITER'



--DISTRIBUTION OF PLANET TYPES


SELECT PLANET_TYPE,COUNT(1)
FROM EXOPLANETS 
GROUP BY 1
ORDER BY 2


--LARGEST EXOPLANETS

SELECT NAME,RADIUS_MULTIPLIER
FROM EXOPLANETS
ORDER BY 2 DESC
LIMIT 10;



--START BRIGHTNESS VS PLANETS

SELECT
stellar_mag AS brightness_bucket,
COUNT(*)
FROM exoplanets
GROUP BY 1
ORDER BY 1;



--DISCOVERY OVER TIME

SELECT discovery_year, COUNT(*)
FROM exoplanets
GROUP BY discovery_year
ORDER BY discovery_year;



--TOP DISCOVERY METHODS


SELECT DETECTION_METHOD,COUNT(*)
FROM EXOPLANETS 
GROUP BY 1
ORDER BY 2 DESC



-- WHICH METHODS FINDS BIGGEST PLANETS

SELECT DETECTION_METHOD,AVG(RADIUS_MULTIPLIER)
FROM EXOPLANETS
GROUP BY 1
ORDER BY 2 DESC;



--ORBITAL SPEED INSIGHT

SELECT name, orbital_period
FROM exoplanets
ORDER BY orbital_period ASC
LIMIT 10;


--DISTANCE ANALYSIS


SELECT 
CASE
	WHEN DISTANCE<100 THEN 'NEAR'
	WHEN DISTANCE DISTANCE <500 THEN 'MID'
	ELSE 'FAR'
END AS DISTANCE_GROUP
FROM EXOPLANETS
ORDER BY 1;



--PLANETS RANKED BY SIZE INSIDE EACH METHOD


SELECT *,
RANK() OVER(PARTITION BY DETECTION_METHOD ORDER BY RADIUS_MULTIPLIER DESC)
FROM EXOPLANETS



--RUNNING DISCOVERIES


SELECT DISCOVERY_YEAR,
COUNT(*) AS YEARLY_COUNT,
SUM(COUNT(*)) OVER(PARTITION BY DISCOVERY_YEAR)
FROM EXOPLANETS
GROUP BY 1;



--EARTH LIKE PLANETS

SELECT *
FROM exoplanets
WHERE radius_multiplier BETWEEN 0.8 AND 1.5
AND orbital_period BETWEEN 200 AND 400;




--OUTLIERS

SELECT *
FROM EXOPLANETS
WHERE MASS_MULTIPLIER>( 

					SELECT AVG(MASS_MULTIPLIER)*5 FROM EXOPLANETS
					
					)